### PR TITLE
Adding http_cache parameter to @viewconfig functions 

### LINKED ISSUE #206: Incorrect user login
Connexions/webview#955

### PR DESCRIPTION
**Pull request by rich-hart**
"When you supply an http_cache value to a view configuration, the Expires and Cache-Control headers of a response generated by the associated view callable are modified. The value for http_cache may be ... zero (0). If the value is zero, the Cache-Control and Expires headers present in all responses from this view will be composed such that client browser cache (__and any intermediate caches__) are instructed to never cache the response."

\- [pyramid view configuration documentation](http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/viewconfig.html)

Fixes #206

### CODE REVIEW

**Comment by rich-hart** [comment]
Are there any suggestions on how a unit test might be written to check the functionally of these new changes?

**Comment by rich-hart** [comment]
Also does there need to be a http_cache = NO_CACHE parameter added here? https://github.com/Connexions/cnx-authoring/blob/1847d78ff76c23733e71a6cf74734cf01171ae4a/cnxauthoring/views.py#L75

**Comment by pumazi** [comment]
Please rebase this. Also, can you confirm the headers through the browsers dev console and paste them here?

**Comment by pumazi** [comment]
@rich-hart Did you mean to close this?

**Comment by rich-hart** [comment]
@pumazi I did, about to reopen another one

**Pull request closed without merging**
