### PR TITLE
store the original license to track changes [Manual DB update needed]

### PR DESCRIPTION
**Pull request by reedstrm**
… detectable The upgrade license code tried to do this, but it's not possible to modify the License json without a lot of work.

### CODE REVIEW

**Comment by karenc** [comment]
Why is this change necessary?

**Comment by reedstrm** [comment]
If we auto-upgrade the license for an author's work, we need to let them know. This change allows webview/authoring to detect that the license has upgraded, so it can do something w/ the UX to let the user know that the license they're agreeing to in the publish pop-up is different than the last time they published this work.

**Comment by karenc** [comment]
```
11:12 < karen> is it so we don't have to make a separate request to archive?
11:12 < karen> you said it's just for the publication popup
11:14 < reedstrm> Right - authoring would have to ask every time it saves - seems excessive. webivew needs to know it for any given document, for both  the metadata page, 
                  and the publishing popup.
11:14 < karen> oh i see
11:16 < karen> oh and the other thing is that we actually display the old license, not just say that it's going to be updated?
11:16 < karen> (because i saw upgraded was already there)
11:23 < reedstrm> @karen, not sure what you mean. WE need to display the license that will be published under, i.e. the new license.
11:23 < karen> we had this: self.assertEqual(document_as_dict['license']['upgraded'], True)
11:24 < karen> that's why i'm wondering if you decided we need to show the details of the old license and so we have to save it
11:26 < reedstrm> Right, that doesn't actually work: at the next level up, the json gets turned back into a model, and the License doesn't have an 'upgraded' field. So it 
                  never makes it to the browser/webview.  Discussed that w/ Rich and MichaelH, decided upgraded license is a property of the document, not the license. And 
                  yes, legacy  gives the author info about both old and new licensees when upgrading, and I like that :-)
```

**Comment by reedstrm** [comment]
DB update requires:
BEGIN WORK;
ALTER TABLE document ADD COLUMN original_license json;
ALTER TABLE document RENAME COLUMN license TO license_text;
ALTER TABLE document ADD COLUMN license json;
UPDATE document set license = replace(license_text,e'\'','"')::json;
ALTER TABLE document ALTER COLUMN license SET NOT NULL;
UPDATE document set original_license = license;
ALTER TABLE document ALTER COLUMN original_license SET NOT NULL;
ALTER TABLE document DROP COLUMN license_text;
COMMIT;

**Pull request merged**
